import type { ConnectorDefinition } from "./types";

const readOperation = (
  id: string,
  label: string,
  capability: ConnectorDefinition["operations"][number]["capability"]
) => ({
  id,
  label,
  capability,
  risk: "read" as const,
  requiresConfirmation: false,
  missionSafe: true,
});

const writeOperation = (
  id: string,
  label: string,
  capability: ConnectorDefinition["operations"][number]["capability"],
  risk: "write" | "publish" | "financial" = "write"
) => ({
  id,
  label,
  capability,
  risk,
  requiresConfirmation: true,
  missionSafe: false,
});

export const connectorCatalog: readonly ConnectorDefinition[] = [
  {
    id: "canva",
    provider: "canva",
    label: "Canva",
    description: "Importer, transformer et exporter des designs sélectionnés par l’utilisateur.",
    category: "design",
    auth: "oauth2",
    runtime: "idealy-server",
    availability: "planned",
    docsUrl: "https://www.canva.dev/docs/connect/",
    authorizationUrl: "https://www.canva.dev/docs/connect/authentication/",
    scopes: ["design:content:read", "design:content:write", "asset:read", "asset:write"],
    operations: [
      readOperation("list-designs", "Lister les designs autorisés", "design-assets-read"),
      readOperation("get-design", "Lire un design sélectionné", "design-assets-read"),
      writeOperation("create-design", "Créer un design", "design-generation"),
      writeOperation("export-design", "Exporter un design", "design-export"),
    ],
    dataBoundary: "user-selected-assets",
    secretEnvNames: ["CANVA_CLIENT_ID", "CANVA_CLIENT_SECRET"],
    notes: [
      "Le site ne doit jamais recevoir le client secret ni les tokens OAuth.",
      "L’intégration Canva de la session d’orchestration ne constitue pas une intégration runtime du site.",
    ],
  },
  {
    id: "github",
    provider: "github",
    label: "GitHub",
    description: "Lire un dépôt sélectionné et publier du code ou des issues après confirmation.",
    category: "code",
    auth: "oauth2",
    runtime: "idealy-server",
    availability: "planned",
    docsUrl: "https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps",
    scopes: ["repo", "read:user"],
    operations: [
      readOperation("list-repositories", "Lister les dépôts autorisés", "repository-read"),
      readOperation("read-repository", "Lire un dépôt sélectionné", "repository-read"),
      writeOperation("create-branch", "Créer une branche", "repository-write"),
      writeOperation("open-pull-request", "Ouvrir une pull request", "repository-write"),
    ],
    dataBoundary: "user-selected-assets",
    secretEnvNames: ["GITHUB_CLIENT_ID", "GITHUB_CLIENT_SECRET"],
    notes: [
      "Les missions peuvent lire un dépôt explicitement choisi, mais ne publient jamais directement sur main.",
      "Toute écriture distante reste confirmée par l’utilisateur.",
    ],
  },
  {
    id: "google-drive",
    provider: "google",
    label: "Google Drive",
    description: "Lister les fichiers Drive explicitement autorisés par le compte Google connecté.",
    category: "data",
    auth: "oauth2",
    runtime: "supabase-edge",
    availability: "planned",
    docsUrl: "https://developers.google.com/identity/protocols/oauth2/web-server",
    scopes: ["https://www.googleapis.com/auth/drive.metadata.readonly"],
    operations: [
      readOperation("list-drive-files", "Lister les fichiers Drive autorisés", "file-storage"),
      readOperation("read-drive-metadata", "Lire les métadonnées d’un fichier sélectionné", "file-storage"),
    ],
    dataBoundary: "user-selected-assets",
    secretEnvNames: ["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET"],
    notes: [
      "Google Drive reste planifié : aucune connexion, lecture ou import Google n’est actif dans cette version.",
      "Le premier scope prévu est limité aux métadonnées Drive en lecture seule ; tout accès au contenu ou toute écriture requiert une revue de scopes distincte.",
      "Les secrets OAuth Google sont exclusivement destinés aux Edge Functions et ne doivent jamais être ajoutés au navigateur ou à Netlify.",
    ],
  },
  {
    id: "vercel",
    provider: "vercel",
    label: "Vercel",
    description: "Créer des previews et déclencher un déploiement après validation de l’utilisateur.",
    category: "deploy",
    auth: "oauth2",
    runtime: "idealy-server",
    availability: "planned",
    docsUrl: "https://vercel.com/docs/integrations",
    scopes: ["project:read", "deployment:read", "deployment:create"],
    operations: [
      readOperation("list-projects", "Lister les projets Vercel", "deployment-preview"),
      readOperation("get-deployment", "Lire le statut d’un déploiement", "deployment-preview"),
      writeOperation("create-preview", "Créer une preview", "deployment-preview", "publish"),
      writeOperation("deploy-production", "Déployer en production", "deployment-production", "publish"),
    ],
    dataBoundary: "metadata-only",
    secretEnvNames: ["VERCEL_CLIENT_ID", "VERCEL_CLIENT_SECRET"],
    notes: [
      "Le bouton de publication doit rester distinct du flux de conversation et demander une confirmation.",
    ],
  },
  {
    id: "supabase",
    provider: "supabase",
    label: "Supabase",
    description: "Lire les ressources du projet Idealy et gérer les données selon les policies RLS.",
    category: "data",
    auth: "managed",
    runtime: "supabase-edge",
    availability: "configured",
    docsUrl: "https://supabase.com/docs/guides/api",
    scopes: ["profile:read", "project:read", "mission:read", "mission-file:read"],
    operations: [
      readOperation("read-mission", "Lire une mission de l’utilisateur", "database-read"),
      readOperation("read-mission-files", "Lire les fichiers d’une mission", "file-storage"),
      writeOperation("append-mission-event", "Ajouter un événement de mission", "database-write"),
    ],
    dataBoundary: "server-managed",
    secretEnvNames: [],
    notes: [
      "Les tokens et la service role key restent côté serveur ou Edge Function.",
      "Les accès utilisateur passent par les policies RLS existantes.",
    ],
  },
  {
    id: "figma",
    provider: "figma",
    label: "Figma",
    description: "Lire des fichiers de design sélectionnés et récupérer leurs métadonnées ou assets.",
    category: "design",
    auth: "oauth2",
    runtime: "idealy-server",
    availability: "planned",
    docsUrl: "https://developers.figma.com/docs/rest-api/",
    scopes: ["file_content:read"],
    operations: [
      readOperation("read-file", "Lire un fichier sélectionné", "design-assets-read"),
      readOperation("export-assets", "Exporter les assets sélectionnés", "design-export"),
    ],
    dataBoundary: "user-selected-assets",
    secretEnvNames: ["FIGMA_CLIENT_ID", "FIGMA_CLIENT_SECRET"],
    notes: ["L’écriture dans Figma n’est pas activée par défaut dans Idealy."],
  },
  {
    id: "notion",
    provider: "notion",
    label: "Notion",
    description: "Lire ou écrire des pages et bases explicitement partagées avec l’intégration.",
    category: "data",
    auth: "oauth2",
    runtime: "idealy-server",
    availability: "planned",
    docsUrl: "https://developers.notion.com/reference/intro",
    scopes: [],
    operations: [
      readOperation("search-pages", "Rechercher les pages partagées", "document-read"),
      readOperation("read-page", "Lire une page sélectionnée", "document-read"),
      writeOperation("append-page", "Ajouter du contenu à une page", "document-write"),
    ],
    dataBoundary: "user-selected-assets",
    secretEnvNames: ["NOTION_CLIENT_ID", "NOTION_CLIENT_SECRET"],
    notes: ["Les permissions restent celles accordées à la page ou à la base Notion."],
  },
  {
    id: "slack",
    provider: "slack",
    label: "Slack",
    description: "Lire un contexte autorisé et envoyer des messages uniquement après confirmation.",
    category: "communication",
    auth: "oauth2",
    runtime: "idealy-server",
    availability: "planned",
    docsUrl: "https://api.slack.com/authentication/oauth-v2",
    scopes: ["channels:read", "chat:write"],
    operations: [
      readOperation("list-channels", "Lister les canaux autorisés", "database-read"),
      writeOperation("send-message", "Envoyer un message", "message-send"),
    ],
    dataBoundary: "metadata-only",
    secretEnvNames: ["SLACK_CLIENT_ID", "SLACK_CLIENT_SECRET"],
    notes: ["L’envoi de message n’est jamais silencieux : il requiert une confirmation explicite."],
  },
  {
    id: "stripe",
    provider: "stripe",
    label: "Stripe",
    description: "Lire l’état de facturation Idealy sans exposer de données sensibles au navigateur.",
    category: "billing",
    auth: "managed",
    runtime: "supabase-edge",
    availability: "configured",
    docsUrl: "https://docs.stripe.com/api",
    scopes: ["billing:read"],
    operations: [
      readOperation("read-subscription", "Lire l’abonnement courant", "billing-read"),
      readOperation("read-invoice", "Lire une facture", "billing-read"),
    ],
    dataBoundary: "server-managed",
    secretEnvNames: [],
    notes: ["Les opérations financières d’écriture restent hors du catalogue mission par défaut."],
  },
];

export function listConnectorDefinitions() {
  return connectorCatalog;
}
