import type { DesignProvider } from "./types";

export const designProviders: DesignProvider[] = [
  {
    category: "ui-system",
    combinesWith: ["radix", "lucide", "motion", "recharts", "tailwind"],
    conflictsWith: ["material-ui", "chakra", "ant-design", "mantine"],
    dependencies: ["tailwindcss"],
    description: "Composants accessibles et composables pilotés par les tokens du projet.",
    frameworks: ["next", "react", "vite"],
    id: "shadcn",
    instructions: ["Use project tokens instead of one-off colors.", "Keep primitives accessible."],
    limitations: ["Requires local component ownership and token discipline."],
    name: "shadcn/ui",
    platforms: ["web", "desktop", "mobile"],
    priority: 100,
    strengths: ["ownership", "accessibility", "composition"],
    suitableFor: ["saas", "dashboard", "marketing", "internal-tool"],
  },
  {
    category: "ui-system",
    combinesWith: ["shadcn", "lucide", "motion", "tailwind"],
    conflictsWith: ["material-ui", "chakra", "ant-design", "mantine"],
    dependencies: ["@radix-ui/react-*"],
    description: "Primitives headless accessibles pour les interactions complexes.",
    frameworks: ["next", "react", "vite"],
    id: "radix",
    instructions: ["Use as behavior primitives, not as a visual system."],
    limitations: ["Needs a visual layer and design tokens."],
    name: "Radix UI",
    platforms: ["web", "desktop"],
    priority: 95,
    strengths: ["accessibility", "interaction", "composability"],
    suitableFor: ["saas", "dashboard", "productivity"],
  },
  {
    category: "ui-system",
    combinesWith: ["material-symbols", "d3", "css-animation"],
    conflictsWith: ["shadcn", "radix", "chakra", "ant-design", "mantine"],
    dependencies: ["@mui/material"],
    description: "Opinionated Material components with a complete visual language.",
    frameworks: ["next", "react", "vite"],
    id: "material-ui",
    instructions: ["Use the Material theme consistently; do not mix another full UI system."],
    limitations: ["Can add bundle weight and a strong visual signature."],
    name: "Material UI",
    platforms: ["web", "desktop", "mobile"],
    priority: 82,
    strengths: ["maturity", "components", "data-heavy-ui"],
    suitableFor: ["enterprise", "dashboard", "admin", "fintech"],
  },
  {
    category: "ui-system",
    combinesWith: ["heroicons", "motion", "recharts"],
    conflictsWith: ["shadcn", "material-ui", "chakra", "ant-design", "mantine"],
    dependencies: ["@chakra-ui/react"],
    description: "Accessible themeable React component system.",
    frameworks: ["next", "react", "vite"],
    id: "chakra",
    instructions: ["Use theme tokens and responsive props consistently."],
    limitations: ["Requires a coherent Chakra theme to avoid generic output."],
    name: "Chakra UI",
    platforms: ["web", "desktop"],
    priority: 76,
    strengths: ["theming", "accessibility", "speed"],
    suitableFor: ["saas", "dashboard", "prototype"],
  },
  {
    category: "ui-system",
    combinesWith: ["lucide", "motion", "echarts"],
    conflictsWith: ["shadcn", "material-ui", "chakra", "mantine"],
    dependencies: ["antd"],
    description: "Broad enterprise component library for dense workflows.",
    frameworks: ["next", "react", "vite"],
    id: "ant-design",
    instructions: ["Favor compact information architecture and explicit feedback states."],
    limitations: ["Opinionated defaults can feel generic without theming."],
    name: "Ant Design",
    platforms: ["web", "desktop"],
    priority: 74,
    strengths: ["enterprise", "forms", "tables"],
    suitableFor: ["admin", "enterprise", "operations"],
  },
  {
    category: "ui-system",
    combinesWith: ["tabler", "motion", "recharts"],
    conflictsWith: ["shadcn", "material-ui", "chakra", "ant-design"],
    dependencies: ["@mantine/core"],
    description: "Themeable React components with strong developer ergonomics.",
    frameworks: ["next", "react", "vite"],
    id: "mantine",
    instructions: ["Use one Mantine theme and its spacing scale."],
    limitations: ["Do not combine with another full component system."],
    name: "Mantine",
    platforms: ["web", "desktop"],
    priority: 73,
    strengths: ["developer-experience", "forms", "theme"],
    suitableFor: ["saas", "dashboard", "internal-tool"],
  },
  {
    category: "ui-system",
    combinesWith: ["tailwind", "headless-ui", "heroicons", "motion"],
    conflictsWith: ["material-ui", "chakra", "ant-design", "mantine"],
    dependencies: ["@headlessui/react"],
    description: "Unstyled accessible interaction primitives for custom Tailwind interfaces.",
    frameworks: ["next", "react", "vite"],
    id: "headless-ui",
    instructions: ["Own the visual layer with project tokens and responsive states."],
    limitations: ["Requires more design implementation than a full system."],
    name: "Headless UI",
    platforms: ["web", "desktop"],
    priority: 78,
    strengths: ["accessibility", "custom-design", "small-surface"],
    suitableFor: ["marketing", "saas", "editorial"],
  },
  {
    category: "ui-system",
    combinesWith: ["phosphor", "motion", "tailwind"],
    conflictsWith: ["shadcn", "material-ui", "chakra", "ant-design", "mantine"],
    dependencies: ["@heroui/react"],
    description: "Polished component set for product surfaces and rapid prototyping.",
    frameworks: ["next", "react", "vite"],
    id: "heroui",
    instructions: ["Use the theme as a whole and preserve keyboard behavior."],
    limitations: ["Avoid mixing with another full UI system."],
    name: "HeroUI / NextUI",
    platforms: ["web", "desktop"],
    priority: 70,
    strengths: ["polish", "speed", "components"],
    suitableFor: ["saas", "marketing", "prototype"],
  },
  {
    category: "design-ai",
    combinesWith: ["shadcn", "radix", "lucide", "motion"],
    conflictsWith: [],
    dependencies: [],
    description: "Design exploration capability for directions, screens and variants.",
    frameworks: ["agnostic"],
    id: "stitch",
    instructions: ["Use only when the capability is configured; preserve the generated design contract."],
    limitations: ["No direct runtime integration is assumed until an official connector is available."],
    name: "Google Stitch",
    platforms: ["web", "mobile", "desktop"],
    priority: 88,
    strengths: ["exploration", "directions", "layout-variants"],
    suitableFor: ["marketing", "saas", "mobile", "prototype"],
  },
  {
    category: "design-ai",
    combinesWith: ["shadcn", "radix", "lucide", "motion"],
    conflictsWith: [],
    dependencies: [],
    description: "Reference capability for rapid product UI exploration.",
    frameworks: ["agnostic"],
    id: "v0",
    instructions: ["Treat output as a design direction and validate it against the project contract."],
    limitations: ["No hidden API or runtime dependency is assumed."],
    name: "v0 design patterns",
    platforms: ["web", "desktop", "mobile"],
    priority: 80,
    strengths: ["product-patterns", "rapid-exploration"],
    suitableFor: ["saas", "marketing", "dashboard"],
  },
  {
    category: "icons",
    combinesWith: ["shadcn", "radix", "motion", "tailwind"],
    conflictsWith: [],
    dependencies: ["lucide-react"],
    description: "Consistent stroke iconography for product interfaces.",
    frameworks: ["next", "react", "vite"],
    id: "lucide",
    instructions: ["Use semantic icons with labels or accessible names."],
    limitations: ["Avoid mixing icon weights without a deliberate hierarchy."],
    name: "Lucide",
    platforms: ["web", "desktop", "mobile"],
    priority: 100,
    strengths: ["consistency", "accessibility", "coverage"],
    suitableFor: ["all"],
  },
  {
    category: "icons",
    combinesWith: ["material-ui", "d3", "css-animation"],
    conflictsWith: [],
    dependencies: ["material-symbols"],
    description: "Material-aligned icon vocabulary for Material products.",
    frameworks: ["next", "react", "vite"],
    id: "material-symbols",
    instructions: ["Use with Material UI when that system is selected."],
    limitations: ["Avoid using as a second icon family beside Lucide without a reason."],
    name: "Material Symbols",
    platforms: ["web", "desktop", "mobile"],
    priority: 76,
    strengths: ["material-language", "coverage"],
    suitableFor: ["enterprise", "dashboard", "android-like"],
  },
  {
    category: "icons",
    combinesWith: ["shadcn", "radix", "motion", "tailwind"],
    conflictsWith: [],
    dependencies: ["@phosphor-icons/react"],
    description: "Expressive icon family with multiple weights for branded interfaces.",
    frameworks: ["next", "react", "vite"],
    id: "phosphor",
    instructions: ["Choose one weight family and keep semantic names for interactive icons."],
    limitations: ["Avoid mixing with another expressive icon family without a deliberate reason."],
    name: "Phosphor Icons",
    platforms: ["web", "desktop", "mobile"],
    priority: 72,
    strengths: ["weights", "expressiveness", "coverage"],
    suitableFor: ["marketing", "saas", "creative", "mobile"],
  },
  {
    category: "icons",
    combinesWith: ["mantine", "motion", "tailwind"],
    conflictsWith: [],
    dependencies: ["@tabler/icons-react"],
    description: "Large open-source icon family with multiple weights.",
    frameworks: ["next", "react", "vite"],
    id: "tabler",
    instructions: ["Choose one weight and keep it consistent."],
    limitations: ["Mixing with multiple icon families reduces coherence."],
    name: "Tabler Icons",
    platforms: ["web", "desktop", "mobile"],
    priority: 70,
    strengths: ["coverage", "weights", "open-source"],
    suitableFor: ["saas", "dashboard", "admin"],
  },
  {
    category: "motion",
    combinesWith: ["shadcn", "radix", "lucide", "recharts", "three"],
    conflictsWith: ["gsap"],
    dependencies: ["framer-motion"],
    description: "React-first motion system for purposeful transitions and feedback.",
    frameworks: ["next", "react", "vite"],
    id: "motion",
    instructions: ["Animate hierarchy and state changes; respect reduced motion."],
    limitations: ["Avoid animating every element or blocking content with transitions."],
    name: "Motion / Framer Motion",
    platforms: ["web", "desktop", "mobile"],
    priority: 96,
    strengths: ["react-integration", "layout", "accessibility"],
    suitableFor: ["saas", "marketing", "editorial", "productivity"],
  },
  {
    category: "motion",
    combinesWith: ["tailwind", "three", "d3"],
    conflictsWith: ["motion"],
    dependencies: ["gsap"],
    description: "Timeline-oriented animation engine for complex sequences.",
    frameworks: ["next", "react", "vite", "agnostic"],
    id: "gsap",
    instructions: ["Use only for timelines or sequences that CSS/Motion cannot express."],
    limitations: ["Do not add for simple state transitions."],
    name: "GSAP",
    platforms: ["web", "desktop"],
    priority: 58,
    strengths: ["timelines", "performance", "canvas"],
    suitableFor: ["marketing", "storytelling", "creative"],
  },
  {
    category: "motion",
    combinesWith: ["shadcn", "motion", "tailwind"],
    conflictsWith: [],
    dependencies: ["lottie-react"],
    description: "Portable authored animation assets for empty states and brand moments.",
    frameworks: ["next", "react", "vite"],
    id: "lottie",
    instructions: ["Use sparingly and provide a static fallback."],
    limitations: ["Asset size and accessibility need review."],
    name: "Lottie",
    platforms: ["web", "desktop", "mobile"],
    priority: 52,
    strengths: ["brand-motion", "illustration"],
    suitableFor: ["onboarding", "marketing", "empty-state"],
  },
  {
    category: "motion",
    combinesWith: ["all"],
    conflictsWith: [],
    dependencies: [],
    description: "Zero-dependency motion baseline for generated applications.",
    frameworks: ["next", "react", "vite", "vue", "svelte", "agnostic"],
    id: "css-animation",
    instructions: ["Prefer transform/opacity and use prefers-reduced-motion."],
    limitations: ["Not suitable for complex orchestration."],
    name: "CSS animations",
    platforms: ["web", "desktop", "mobile"],
    priority: 90,
    strengths: ["bundle-size", "portability", "performance"],
    suitableFor: ["all"],
  },
  {
    category: "charts",
    combinesWith: ["shadcn", "material-ui", "motion", "lucide"],
    conflictsWith: [],
    dependencies: ["recharts"],
    description: "React-native declarative charts for common product analytics.",
    frameworks: ["next", "react", "vite"],
    id: "recharts",
    instructions: ["Use accessible labels, responsive containers and restrained color scales."],
    limitations: ["Less suitable for highly custom scientific visualization."],
    name: "Recharts",
    platforms: ["web", "desktop"],
    priority: 88,
    strengths: ["product-analytics", "react", "speed"],
    suitableFor: ["dashboard", "fintech", "saas"],
  },
  {
    category: "charts",
    combinesWith: ["material-ui", "tailwind", "motion"],
    conflictsWith: [],
    dependencies: ["echarts"],
    description: "Feature-rich charting for dense dashboards and interactions.",
    frameworks: ["next", "react", "vite"],
    id: "echarts",
    instructions: ["Keep chart interactions keyboard-accessible and mobile-safe."],
    limitations: ["Can be heavier than a focused chart library."],
    name: "Apache ECharts",
    platforms: ["web", "desktop"],
    priority: 80,
    strengths: ["breadth", "interaction", "dashboard"],
    suitableFor: ["fintech", "analytics", "operations"],
  },
  {
    category: "charts",
    combinesWith: ["shadcn", "radix", "motion"],
    conflictsWith: [],
    dependencies: ["d3"],
    description: "Low-level data visualization primitives for bespoke visualizations.",
    frameworks: ["next", "react", "vite", "agnostic"],
    id: "d3",
    instructions: ["Keep scales and rendering separate; provide tabular alternatives."],
    limitations: ["Higher implementation cost than declarative chart systems."],
    name: "D3",
    platforms: ["web", "desktop"],
    priority: 78,
    strengths: ["customization", "expressiveness", "data"],
    suitableFor: ["data-product", "scientific", "editorial"],
  },
  {
    category: "three-d",
    combinesWith: ["react-three-fiber", "drei", "motion", "css-animation"],
    conflictsWith: [],
    dependencies: ["three"],
    description: "WebGL scene capability for cases where spatial interaction adds product value.",
    frameworks: ["next", "react", "vite"],
    id: "three",
    instructions: ["Only activate for explicit requests or clear spatial value; include fallback."],
    limitations: ["Performance, mobile and accessibility require explicit review."],
    name: "Three.js",
    platforms: ["web", "desktop"],
    priority: 45,
    strengths: ["3d", "webgl", "creative"],
    suitableFor: ["gaming", "portfolio", "architecture", "immersive"],
  },
  {
    category: "three-d",
    combinesWith: ["three", "drei", "motion"],
    conflictsWith: [],
    dependencies: ["@react-three/fiber"],
    description: "React renderer for Three.js scenes.",
    frameworks: ["next", "react", "vite"],
    id: "react-three-fiber",
    instructions: ["Keep the canvas isolated and preserve non-WebGL content."],
    limitations: ["Requires React/WebGL and careful hydration boundaries."],
    name: "React Three Fiber",
    platforms: ["web", "desktop"],
    priority: 43,
    strengths: ["react", "scene-composition"],
    suitableFor: ["gaming", "creative", "immersive"],
  },
  {
    category: "three-d",
    combinesWith: ["three", "react-three-fiber", "motion"],
    conflictsWith: [],
    dependencies: ["@react-three/drei"],
    description: "Reusable helpers for cameras, controls, loaders and environments.",
    frameworks: ["next", "react", "vite"],
    id: "drei",
    instructions: ["Use only the helpers required by the scene; provide loading/error states."],
    limitations: ["Not useful without a Three.js scene."],
    name: "Drei",
    platforms: ["web", "desktop"],
    priority: 40,
    strengths: ["scene-helpers", "developer-experience"],
    suitableFor: ["gaming", "creative", "immersive"],
  },
];

const providerMap = new Map(designProviders.map((provider) => [provider.id, provider]));

export function getDesignProvider(id: string) {
  return providerMap.get(id);
}

export function listDesignProviders() {
  return [...designProviders];
}
