import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

async function githubFetch(url: string, token: string, options: RequestInit = {}) {
  const res = await fetch(url, {
    ...options,
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      ...(options.headers ?? {}),
    },
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.message ?? `GitHub error ${res.status}`);
  return data;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Use service role for admin DB operations
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Verify user with anon client
    const anonClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? ''
    );
    const { data: { user } } = await anonClient.auth.getUser(authHeader.replace('Bearer ', ''));
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const { projectName, files } = await req.json();

    // Get user's GitHub token from integrations table
    const { data: integration } = await supabase
      .from('integrations')
      .select('access_token')
      .eq('user_id', user.id)
      .eq('provider', 'github')
      .single();

    if (!integration?.access_token) {
      return new Response(JSON.stringify({ error: 'GitHub not connected. Please connect GitHub in Connectors.' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const token = integration.access_token;
    const repoName = projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/^-+|-+$/g, '');

    // 1. Create repository
    const repo = await githubFetch('https://api.github.com/user/repos', token, {
      method: 'POST',
      body: JSON.stringify({
        name: repoName,
        description: 'Generated by Idealy — https://idealy.app',
        private: false,
        auto_init: true,
      }),
    });

    const owner = repo.owner.login;
    const repoFullName = repo.full_name;

    // 2. Get default branch SHA (from auto_init commit)
    const branchData = await githubFetch(
      `https://api.github.com/repos/${repoFullName}/git/ref/heads/${repo.default_branch}`,
      token
    );
    const baseTreeSHA = branchData.object.sha;

    // 3. Get base tree SHA
    const commitData = await githubFetch(
      `https://api.github.com/repos/${repoFullName}/git/commits/${baseTreeSHA}`,
      token
    );
    const baseTree = commitData.tree.sha;

    // 4. Create blobs for all files in parallel
    const blobPromises = Object.entries(files as Record<string, string>).map(async ([path, content]) => {
      const blob = await githubFetch(
        `https://api.github.com/repos/${repoFullName}/git/blobs`,
        token,
        {
          method: 'POST',
          body: JSON.stringify({
            content: btoa(unescape(encodeURIComponent(content))),
            encoding: 'base64',
          }),
        }
      );
      return { path: path.startsWith('/') ? path.slice(1) : path, mode: '100644', type: 'blob', sha: blob.sha };
    });

    const treeItems = await Promise.all(blobPromises);

    // 5. Create a single tree with all files (atomic)
    const newTree = await githubFetch(
      `https://api.github.com/repos/${repoFullName}/git/trees`,
      token,
      {
        method: 'POST',
        body: JSON.stringify({ base_tree: baseTree, tree: treeItems }),
      }
    );

    // 6. Create commit
    const newCommit = await githubFetch(
      `https://api.github.com/repos/${repoFullName}/git/commits`,
      token,
      {
        method: 'POST',
        body: JSON.stringify({
          message: `🚀 Initial commit — Generated by Idealy`,
          tree: newTree.sha,
          parents: [baseTreeSHA],
        }),
      }
    );

    // 7. Update branch ref
    await githubFetch(
      `https://api.github.com/repos/${repoFullName}/git/refs/heads/${repo.default_branch}`,
      token,
      {
        method: 'PATCH',
        body: JSON.stringify({ sha: newCommit.sha }),
      }
    );

    return new Response(JSON.stringify({ repoUrl: repo.html_url, owner, repo: repoName }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});